//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServiceReferenceProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProducto.IServiceProducto")]
    public interface IServiceProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/AddProducto", ReplyAction="http://tempuri.org/IServiceProducto/AddProductoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SL_WCF.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        SL_WCF.Result AddProducto(ML.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/AddProducto", ReplyAction="http://tempuri.org/IServiceProducto/AddProductoResponse")]
        System.Threading.Tasks.Task<SL_WCF.Result> AddProductoAsync(ML.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/UpdateProducto", ReplyAction="http://tempuri.org/IServiceProducto/UpdateProductoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SL_WCF.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        SL_WCF.Result UpdateProducto(ML.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/UpdateProducto", ReplyAction="http://tempuri.org/IServiceProducto/UpdateProductoResponse")]
        System.Threading.Tasks.Task<SL_WCF.Result> UpdateProductoAsync(ML.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/DeleteProducto", ReplyAction="http://tempuri.org/IServiceProducto/DeleteProductoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        SL_WCF.Result DeleteProducto(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/DeleteProducto", ReplyAction="http://tempuri.org/IServiceProducto/DeleteProductoResponse")]
        System.Threading.Tasks.Task<SL_WCF.Result> DeleteProductoAsync(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/GetAllProducto", ReplyAction="http://tempuri.org/IServiceProducto/GetAllProductoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        SL_WCF.Result GetAllProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/GetAllProducto", ReplyAction="http://tempuri.org/IServiceProducto/GetAllProductoResponse")]
        System.Threading.Tasks.Task<SL_WCF.Result> GetAllProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/GetByIdProducto", ReplyAction="http://tempuri.org/IServiceProducto/GetByIdProductoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Producto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Departamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Proveedor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        SL_WCF.Result GetByIdProducto(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/GetByIdProducto", ReplyAction="http://tempuri.org/IServiceProducto/GetByIdProductoResponse")]
        System.Threading.Tasks.Task<SL_WCF.Result> GetByIdProductoAsync(int IdProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProductoChannel : PL.ServiceReferenceProducto.IServiceProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProductoClient : System.ServiceModel.ClientBase<PL.ServiceReferenceProducto.IServiceProducto>, PL.ServiceReferenceProducto.IServiceProducto {
        
        public ServiceProductoClient() {
        }
        
        public ServiceProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SL_WCF.Result AddProducto(ML.Producto producto) {
            return base.Channel.AddProducto(producto);
        }
        
        public System.Threading.Tasks.Task<SL_WCF.Result> AddProductoAsync(ML.Producto producto) {
            return base.Channel.AddProductoAsync(producto);
        }
        
        public SL_WCF.Result UpdateProducto(ML.Producto producto) {
            return base.Channel.UpdateProducto(producto);
        }
        
        public System.Threading.Tasks.Task<SL_WCF.Result> UpdateProductoAsync(ML.Producto producto) {
            return base.Channel.UpdateProductoAsync(producto);
        }
        
        public SL_WCF.Result DeleteProducto(int IdProducto) {
            return base.Channel.DeleteProducto(IdProducto);
        }
        
        public System.Threading.Tasks.Task<SL_WCF.Result> DeleteProductoAsync(int IdProducto) {
            return base.Channel.DeleteProductoAsync(IdProducto);
        }
        
        public SL_WCF.Result GetAllProducto() {
            return base.Channel.GetAllProducto();
        }
        
        public System.Threading.Tasks.Task<SL_WCF.Result> GetAllProductoAsync() {
            return base.Channel.GetAllProductoAsync();
        }
        
        public SL_WCF.Result GetByIdProducto(int IdProducto) {
            return base.Channel.GetByIdProducto(IdProducto);
        }
        
        public System.Threading.Tasks.Task<SL_WCF.Result> GetByIdProductoAsync(int IdProducto) {
            return base.Channel.GetByIdProductoAsync(IdProducto);
        }
    }
}
